apiVersion: apps/v1
kind: Deployment
metadata:
  name: play-scala-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: play-scala-app
  template:
    metadata:
      labels:
        app: play-scala-app
    spec:
      containers:
      - name: play-scala-app
        image: us-central1-docker.pkg.dev/wilmoth-example/my-repo/play-scala-app:latest
        ports:
        - containerPort: 9000